name: Android CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List directory contents
        run: ls -la

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          java-package: jdk
          check-latest: false

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install Bundler
        run: gem install bundler

      - name: Install Fastlane and dependencies
        run: cd android && bundle install

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20'

      - name: Install Node.js dependencies
        run: yarn install

      - name: Check Firebase service credentials
        run: echo "$FIREBASE_SERVICE_CREDENTIALS_JSON"

      - name: Set up Firebase service credentials
        env:
          FIREBASE_SERVICE_CREDENTIALS_JSON: ${{ secrets.FIREBASE_SERVICE_CREDENTIALS_JSON }}
        run: |
          echo "$FIREBASE_SERVICE_CREDENTIALS_JSON" | base64 --decode > ./android/fastlane/firebase_credentials.json

      - name: Print Firebase service credentials file
        run: cat ./android/fastlane/firebase_credentials.json

      - name: Deploy to Firebase
        env:
          FIREBASE_SERVICE_CREDENTIALS_JSON: ${{ secrets.FIREBASE_SERVICE_CREDENTIALS_JSON }}
        run: cd android && bundle exec fastlane deploy_android_to_firebase