name: Android CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List directory contents
        run: ls -la

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
          java-package: jdk
          check-latest: false

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install Fastlane
        run: gem install fastlane

      - name: Create fastlane directory
        run: mkdir -p ./fastlane

      - name: Check Firebase service credentials
        run: echo "$FIREBASE_SERVICE_CREDENTIALS_JSON"

      - name: Set up Firebase service credentials
        env:
          FIREBASE_SERVICE_CREDENTIALS_JSON: ${{ secrets.FIREBASE_SERVICE_CREDENTIALS_JSON }}
        run: |
          echo "$FIREBASE_SERVICE_CREDENTIALS_JSON" | base64 --decode > ./fastlane/firebase_credentials.json

      - name: Deploy to Firebase
        env:
          FIREBASE_SERVICE_CREDENTIALS_JSON: './fastlane/firebase_credentials.json'
        run: bundle exec fastlane deploy_android_to_firebase